base_url: "https://pycord.crowdin.com"
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN

preserve_hierarchy: true

commit_message: "docs: Update translations"

export_languages: ["de", "ja", "fr", "it", "hi", "ko", "pt-BR", "es-ES", "zh-CN", "ru"]

files:
  - source: /i18n/en/**/*
    translation: /i18n/%two_letters_code%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /src/pages/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-pages%original_file_name%