/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    "index",
    {
      type: 'category',
      label: 'Getting Started',
      items: ["Getting Started/installation", "Getting Started/creating-your-first-bot"],
    },
    {
      type: 'category',
      label: "Interactions",
      items: ["Interactions/buttons", "Interactions/slash-commands"]
    },
    {
      type: 'category',
      label: "Extensions",
      items: [
        {
          type: 'category',
          label: "Commands",
          items: ["Extensions/Commands/index"]
        },
        {
          type: 'category',
          label: "Pages",
          items: ["Extensions/Pages/index"]
        }
      ]
    },
    {
      type: 'category',
      label: "Voice",
      link: { type: "doc", id: "Voice/index" },
      items: ["Voice/receiving"],
    },
    {
      type: 'category',
      label: "Topics",
      items: ["Topics/community-resources"]
    }
  ],

};

module.exports = sidebars;
