on: push
name: Checks
jobs:
  lint-and-typecheck:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Typecheck
      uses: CultureHQ/actions-yarn@master
      with:
        args: typecheck
    - name: Lint
      uses: CultureHQ/actions-yarn@master
      with:
        args: check
